<?php
/**
 * This file is part of Vima PHP.
 *
 * (c) Vima PHP <https://github.com/vimaphp>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace Vima\Core\Services;

use Vima\Core\Config\Setup;

/**
 * Class MapGenerator
 * 
 * Generates PHP mapper classes from Setup configuration using MappingService.
 */
class MapGenerator
{
    public function __construct(private MappingService $mappingService)
    {
    }

    /**
     * Generate Roles class content.
     */
    public function generateRoles(Setup $setup, string $namespace): string
    {
        $roleNames = array_map(fn($role) => $role->name, $setup->roles);
        $this->mappingService->sync($roleNames, 'roles');
        $this->mappingService->save();

        return $this->renderClass('Roles', $namespace, $this->mappingService->all('roles'));
    }

    /**
     * Generate Permissions class content.
     */
    public function generatePermissions(Setup $setup, string $namespace): string
    {
        $permissionNames = array_map(fn($perm) => $perm->name, $setup->permissions);

        // Also collect permissions defined within roles
        foreach ($setup->roles as $role) {
            foreach ($role->permissions as $perm) {
                // FIX: Issue #3
                if (!in_array($perm->name, $permissionNames) && !str_contains($perm->name, '*')) {
                    $permissionNames[] = $perm->name;
                }
            }
        }

        $this->mappingService->sync($permissionNames, 'permissions');
        $this->mappingService->save();

        return $this->renderClass('Permissions', $namespace, $this->mappingService->all('permissions'));
    }

    /**
     * Render the PHP class content.
     */
    private function renderClass(string $className, string $namespace, array $items): string
    {
        $php = "<?php\n";
        $php .= "/**\n";
        $php .= " * This file is part of Vima PHP.\n";
        $php .= " *\n";
        $php .= " * (c) Vima PHP <https://github.com/vimaphp>\n";
        $php .= " *\n";
        $php .= " * For the full copyright and license information, please view the LICENSE\n";
        $php .= " * file that was distributed with this source code.\n";
        $php .= " * Do not edit this file manually, instead use the framework defined commands to automatically generate it\n";
        $php .= " */\n\n";
        $php .= "declare(strict_types=1);\n\n";
        $php .= "namespace " . ltrim($namespace, '\\') . ";\n\n";
        $php .= "/**\n";
        $php .= " * Generated by Vima Mapper. Do not edit manually.\n";
        $php .= " */\n";
        $php .= "final class {$className}\n";
        $php .= "{\n";

        ksort($items);

        foreach ($items as $slug => $name) {
            $php .= "    public const {$slug} = '{$name}';\n";
        }

        $php .= "}\n";

        return $php;
    }
}
