<?php
/**
 * This file is part of Vima PHP.
 *
 * (c) Vima PHP <https://github.com/vimaphp>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace Vima\Core\Services;

use Vima\Core\Config\Setup;
use Vima\Core\Contracts\EventDispatcherInterface;
use Vima\Core\Events\DefaultEventDispatcher;
use Vima\Core\Events\Mapping\MapGenerated;

/**
 * Class MapGenerator
 * 
 * Generates PHP mapper classes from Setup configuration using MappingService.
 */
class MapGenerator
{
    public function __construct(
        private MappingService $mappingService,
        private ?EventDispatcherInterface $dispatcher = null
    ) {
        $this->dispatcher ??= new DefaultEventDispatcher();
    }

    /**
     * Generate Roles class content.
     */
    public function generateRoles(Setup $setup, string $namespace): string
    {
        $roleNames = array_map(fn($role) => $role->namespace ? $role->namespace . ':' . $role->name : $role->name, $setup->roles);
        $this->mappingService->sync($roleNames, 'roles');
        $this->mappingService->save();

        $map = $this->mappingService->all('roles');
        $this->dispatcher->dispatch(new MapGenerated('roles', $map));

        return $this->renderClass('Roles', $namespace, $map);
    }

    /**
     * Generate Permissions class content.
     */
    public function generatePermissions(Setup $setup, string $namespace): string
    {
        $permissionNames = array_map(fn($perm) => $perm->namespace ? $perm->namespace . ':' . $perm->name : $perm->name, $setup->permissions);

        // Also collect permissions defined within roles
        foreach ($setup->roles as $role) {
            foreach ($role->permissions as $perm) {
                $name = $perm->namespace ? $perm->namespace . ':' . $perm->name : $perm->name;
                if (!in_array($name, $permissionNames) && !str_contains($perm->name, '*')) {
                    $permissionNames[] = $name;
                }
            }
        }

        $this->mappingService->sync($permissionNames, 'permissions');
        $this->mappingService->save();

        $map = $this->mappingService->all('permissions');
        $this->dispatcher->dispatch(new MapGenerated('permissions', $map));

        return $this->renderClass('Permissions', $namespace, $map);
    }

    /**
     * Generate Namespaces class content.
     */
    public function generateNamespaces(string $namespace): string
    {
        $map = $this->mappingService->all('namespaces');
        return $this->renderClass('Namespaces', $namespace, $map);
    }

    /**
     * Render the PHP class content.
     */
    private function renderClass(string $className, string $namespace, array $items): string
    {
        $php = "<?php\n";
        $php .= "/**\n";
        $php .= " * This file is part of Vima PHP.\n";
        $php .= " *\n";
        $php .= " * (c) Vima PHP <https://github.com/vimaphp>\n";
        $php .= " *\n";
        $php .= " * For the full copyright and license information, please view the LICENSE\n";
        $php .= " * file that was distributed with this source code.\n";
        $php .= " * Do not edit this file manually, instead use the framework defined commands to automatically generate it\n";
        $php .= " */\n\n";
        $php .= "declare(strict_types=1);\n\n";
        $php .= "namespace " . ltrim($namespace, '\\') . ";\n\n";
        $php .= "use Vima\Core\Mappers\EnumMapper;\n";
        $php .= "/**\n";
        $php .= " * Generated by Vima Mapper. Do not edit manually.\n";
        $php .= " */\n";
        $php .= "final class {$className} extends EnumMapper\n";
        $php .= "{\n";

        ksort($items);

        foreach ($items as $slug => $name) {
            $php .= "    public const string {$slug} = '{$name}';\n";
        }

        $php .= "}\n";

        return $php;
    }
}
